INSERT INTO t_stats_trades
        (ind, dir, o_dt, c_dt)
WITH CTE AS
        (SELECT IND, SIG, DT, 
         (DENSE_RANK() OVER (PARTITION BY YEAR(dt), DAYOFYEAR(dt), IND 
          ORDER BY DT) - DENSE_RANK() OVER (PARTITION BY YEAR(dt), DAYOFYEAR(dt), IND, SIG ORDER BY DT)) GRP
          FROM t_stats_csv
        ORDER BY YEAR(dt), DAYOFYEAR(dt), IND, DT, SIG),
     CTE2 AS
        (SELECT ROW_NUMBER() OVER (PARTITION BY YEAR(dt), DAYOFYEAR(dt), IND ORDER BY IND) ROWNUM, IND, SIG, MIN(DT) START
          FROM CTE
          GROUP BY YEAR(dt), DAYOFYEAR(dt), IND, SIG, GRP
          ORDER BY YEAR(dt), DAYOFYEAR(dt), IND, START),
     cteSIG1 AS
    (SELECT ROWNUM, IND, SIG, START
      FROM CTE2
      WHERE SIG = 1
          ORDER BY IND, START),
     cteSIG3 AS
    (SELECT ROWNUM, IND, SIG, START
      FROM CTE2
      WHERE SIG = 3
      ORDER BY IND, START),
     cteS AS
    (SELECT J1.IND IND, "S" DIR, J1.START O_DT, J2.START C_DT
      FROM cteSIG1 J1
      JOIN cteSIG3 J2 ON J2.ROWNUM = J1.ROWNUM + 1
      WHERE DATE(J1.START) = DATE(J2.START)),
     cteL AS
    (SELECT J2.IND IND, "L" DIR, J2.START O_DT, J1.START C_DT
      FROM cteSIG1 J1
      JOIN cteSIG3 J2 ON J1.ROWNUM = J2.ROWNUM + 1
      WHERE DATE(J1.START) = DATE(J2.START))
SELECT IND, DIR, O_DT, C_DT
FROM  cteS
UNION ALL
SELECT IND, DIR, O_DT, C_DT
FROM  cteL
ORDER BY IND, DIR, O_DT