-- the tables used in the src/test/resources/window/* unit tests

CREATE TABLE w1(i INT, j INT);
INSERT INTO w1 VALUES (1,1);
INSERT INTO w1 VALUES (1,4);
INSERT INTO w1 VALUES (1,2);
INSERT INTO w1 VALUES (1,4);

CREATE TABLE threeCol(i INT, j INT, k INT);
INSERT INTO threeCol VALUES (1,1,1);
INSERT INTO threeCol VALUES (1,4,1);
INSERT INTO threeCol VALUES (1,2,1);
INSERT INTO threeCol VALUES (1,4,1);
INSERT INTO threeCol VALUES (1,4,1);
INSERT INTO threeCol VALUES (1,1,2);
INSERT INTO threeCol VALUES (1,4,2);
INSERT INTO threeCol VALUES (1,2,2);
INSERT INTO threeCol VALUES (1,4,2);
INSERT INTO threeCol VALUES (1,1,3);
INSERT INTO threeCol VALUES (1,4,3);
INSERT INTO threeCol VALUES (1,2,3);
INSERT INTO threeCol VALUES (1,4,3);
INSERT INTO threeCol VALUES (1,1,4);
INSERT INTO threeCol VALUES (1,4,4);
INSERT INTO threeCol VALUES (1,2,4);
INSERT INTO threeCol VALUES (1,4,4);

CREATE TABLE testAB (id INTEGER, c CHAR(1));
INSERT INTO testAB VALUES (1, 'A');
INSERT INTO testAB VALUES (2, 'B');
INSERT INTO testAB VALUES (3, 'B');
INSERT INTO testAB VALUES (4, 'B');
INSERT INTO testAB VALUES (5, 'A');
INSERT INTO testAB VALUES (10, NULL);
INSERT INTO testAB VALUES (11, NULL);

CREATE TABLE justA(c CHAR(1));
INSERT INTO justA VALUES ('A');



